name: Deploy

on:
  workflow_dispatch:

inputs:
  email:
    description: "Atlassian account email"
    required: true
  apiToken:
    description: "Atlassian API token"
    required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Forge CLI
        run: npm install -g @forge/cli
      - name: Install dependencies in Forge Root Project
        run: npm install
      - name: Install dependencies in Forge Custom UI Project
        run: npm install
        working-directory: ./static/onlyoffice-jira-docs-forge-custom-ui
      - name: Build Forge Custom UI Project
        run: npm run build
        working-directory: ./static/onlyoffice-jira-docs-forge-custom-ui
      - name: Deploy Forge app
        run: forge deploy --non-interactive
        env:
          FORGE_EMAIL: ${{ inputs.email }}
          FORGE_API_TOKEN: ${{ inputs.apiToken }}
      