version: '3'

services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: onlyoffice_docs_atlassian_cloud
      POSTGRES_USER: onlyoffice
      POSTGRES_PASSWORD: onlyoffice
    ports:
      - "5432:5432"
  redis:
    image: redis:7.0.12
    environment:
      REDIS_PASSWORD: redis
    ports:
      - "6379:6379"