name: CI for remote

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches: [master, develop]
    paths:
      - 'remote/**/*.java'
      - 'remote/**/*.yml'
      - 'remote/**/*.xml'
  push:
    branches: [master, develop]
    paths:
      - 'remote/**/*.java'
      - 'remote/**/*.yml'
      - 'remote/**/*.xml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run Code Style Checks
        run: |
          cd ${{ github.workspace }}/remote
          mvn --batch-mode checkstyle:check
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run Tests
        run: |
          cd ${{ github.workspace }}/remote
          mvn --batch-mode test